### ISSUE TITLE
Your first functional version could be more clear

### ISSUE THREAD

**Issue by RasmusWL** [pdubroy/manuel#1]
The code 

```
var newState =
    drawManuel(
    drawBackground(
    processInput(state)));
```

could be written as the following, clearly showing we are only modifying state in `processInput`

```
var newState = processInput(state);
drawManuel(newState);
drawBackground(newState);
```

**Comment by pdubroy** [comment]
Yep, that would make the dependencies more clear. However, I'd like the code in this repository to reflect what was published in the article.
